"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class RobotStatus(object):

    __slots__ = ["completed"]

    __typenames__ = ["boolean"]

    __dimensions__ = [None]

    def __init__(self):
        self.completed = False
        """ LCM Type: boolean """

    def encode(self):
        buf = BytesIO()
        buf.write(RobotStatus._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">b", self.completed))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != RobotStatus._get_packed_fingerprint():
            raise ValueError("Decode error")
        return RobotStatus._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = RobotStatus()
        self.completed = bool(struct.unpack('b', buf.read(1))[0])
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if RobotStatus in parents: return 0
        tmphash = (0xc298c3b7d1ae3ccc) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if RobotStatus._packed_fingerprint is None:
            RobotStatus._packed_fingerprint = struct.pack(">Q", RobotStatus._get_hash_recursive([]))
        return RobotStatus._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", RobotStatus._get_packed_fingerprint())[0]

